/**
 * Map country codes (from projects) to standardized country names (for map data)
 * This ensures the project data country codes match the names in the world map TopoJSON
 */
export const useCountryMapping = () => {
  // Map from our country codes to World Atlas country names
  const countryCodeToMapName: Record<string, string> = {
    // Keep keys lowercase as they come from project data
    afghanistan: 'Afghanistan',
    albania: 'Albania',
    algeria: 'Algeria',
    argentina: 'Argentina',
    armenia: 'Armenia',
    australia: 'Australia',
    austria: 'Austria',
    bangladesh: 'Bangladesh',
    belgium: 'Belgium',
    bolivia: 'Bolivia',
    brazil: 'Brazil',
    bulgaria: 'Bulgaria',
    burkina: 'Burkina Faso',
    'burma-myanmar': 'Myanmar',
    cambodia: 'Cambodia',
    cameroon: 'Cameroon',
    canada: 'Canada',
    chile: 'Chile',
    china: 'China',
    colombia: 'Colombia',
    'congo-democratic-republic-of': 'Dem. Rep. Congo',
    congo: 'Congo',
    'costa-rica': 'Costa Rica',
    'ivory-coast': "Côte d'Ivoire",
    croatia: 'Croatia',
    cuba: 'Cuba',
    cyprus: 'Cyprus',
    'czech-republic': 'Czech Rep.',
    denmark: 'Denmark',
    'dominican-republic': 'Dominican Rep.',
    ecuador: 'Ecuador',
    egypt: 'Egypt',
    'el-salvador': 'El Salvador',
    estonia: 'Estonia',
    ethiopia: 'Ethiopia',
    finland: 'Finland',
    france: 'France',
    georgia: 'Georgia',
    germany: 'Germany',
    ghana: 'Ghana',
    greece: 'Greece',
    guatemala: 'Guatemala',
    haiti: 'Haiti',
    honduras: 'Honduras',
    'hong-kong': 'Hong Kong',
    hungary: 'Hungary',
    iceland: 'Iceland',
    india: 'India',
    indonesia: 'Indonesia',
    iran: 'Iran',
    iraq: 'Iraq',
    ireland: 'Ireland',
    israel: 'Israel',
    italy: 'Italy',
    jamaica: 'Jamaica',
    japan: 'Japan',
    jordan: 'Jordan',
    kazakhstan: 'Kazakhstan',
    kenya: 'Kenya',
    'korea-south': 'South Korea',
    'korea-north': 'North Korea',
    kuwait: 'Kuwait',
    kyrgyzstan: 'Kyrgyzstan',
    laos: 'Laos',
    latvia: 'Latvia',
    lebanon: 'Lebanon',
    libya: 'Libya',
    lithuania: 'Lithuania',
    luxembourg: 'Luxembourg',
    madagascar: 'Madagascar',
    malawi: 'Malawi',
    malaysia: 'Malaysia',
    mali: 'Mali',
    mexico: 'Mexico',
    moldova: 'Moldova',
    mongolia: 'Mongolia',
    morocco: 'Morocco',
    mozambique: 'Mozambique',
    namibia: 'Namibia',
    nepal: 'Nepal',
    netherlands: 'Netherlands',
    'new-zealand': 'New Zealand',
    nicaragua: 'Nicaragua',
    niger: 'Niger',
    nigeria: 'Nigeria',
    norway: 'Norway',
    pakistan: 'Pakistan',
    palestine: 'Palestine',
    panama: 'Panama',
    paraguay: 'Paraguay',
    peru: 'Peru',
    philippines: 'Philippines',
    poland: 'Poland',
    portugal: 'Portugal',
    romania: 'Romania',
    'russian-federation': 'Russia',
    rwanda: 'Rwanda',
    'saudi-arabia': 'Saudi Arabia',
    senegal: 'Senegal',
    serbia: 'Serbia',
    singapore: 'Singapore',
    slovakia: 'Slovakia',
    slovenia: 'Slovenia',
    somalia: 'Somalia',
    'south-africa': 'South Africa',
    'south-sudan': 'S. Sudan',
    spain: 'Spain',
    'sri-lanka': 'Sri Lanka',
    sudan: 'Sudan',
    sweden: 'Sweden',
    switzerland: 'Switzerland',
    syria: 'Syria',
    taiwan: 'Taiwan',
    tajikistan: 'Tajikistan',
    tanzania: 'Tanzania',
    thailand: 'Thailand',
    togo: 'Togo',
    tunisia: 'Tunisia',
    turkey: 'Turkey',
    turkmenistan: 'Turkmenistan',
    uganda: 'Uganda',
    ukraine: 'Ukraine',
    'united-arab-emirates': 'United Arab Emirates',
    'united-kingdom': 'United Kingdom',
    'united-states': 'United States of America',
    uruguay: 'Uruguay',
    uzbekistan: 'Uzbekistan',
    venezuela: 'Venezuela',
    vietnam: 'Vietnam',
    yemen: 'Yemen',
    zambia: 'Zambia',
    zimbabwe: 'Zimbabwe'
  }

  const mapNameToCountryCode = Object.fromEntries(
    Object.entries(countryCodeToMapName).map(([code, name]) => [name.toLowerCase(), code])
  )

  return {
    countryCodeToMapName,
    mapNameToCountryCode,
    getMapName: (code: string) => countryCodeToMapName[code.toLowerCase()],
    getCountryCode: (mapName: string) => mapNameToCountryCode[mapName.toLowerCase()]
  }
}
